package hicks.td.util;

public enum BodyPart
{
    BODY_HUMAN,
    BODY_SKELETON,
    BACK_QUIVER,
    BELT_LEATHER,
    BELT_ROPE,
    FEET_PLATE,
    FEET_SHOES,
    HANDS_PLATE,
    HEAD_CHAIN_HELMET,
    HEAD_CHAIN_HOOD,
    HEAD_HAIR,
    HEAD_LEATHER_HAT,
    HEAD_PLATE,
    HEAD_ROBE,
    LEGS_PANTS,
    LEGS_PLATE,
    LEGS_ROBE,
    TORSO_CHAIN_JACKET,
    TORSO_CHAIN_ARMOR,
    TORSO_LEATHER_BRACERS,
    TORSO_LEATHER_SHIRT,
    TORSO_LEATHER_SHOULDERS,
    TORSO_LEATHER_ARMOR,
    TORSO_PLATE_SHOULDERS,
    TORSO_PLATE,
    TORSO_ROBE
}
